## Libraries

In [1]:
import pandas as pd
# Pandas
# It used for Handling data (particularly for large scale data)
df = pd.read_csv('survey_results_schema.csv')
print(df)


       qid                 qname  \
0   QID281       LearnCodeOnline   
1   QID306  LearnCodeCoursesCert   
2    QID32             YearsCode   
3    QID34          YearsCodePro   
4    QID31               DevType   
5    QID29               OrgSize   
6   QID278     PurchaseInfluence   
7   QID322              TechList   
8   QID279            BuyNewTool   
9     QID6               Country   
10   QID50              Currency   
11   QID51             CompTotal   
12   QID61                    S3   
13  QID233              Language   
14  QID262              Database   
15  QID263              Platform   
16  QID264              Webframe   
17  QID265              MiscTech   
18  QID275             ToolsTech   
19  QID274        NEWCollabTools   
20   QID71                 OpSys   
21  QID282      OfficeStackAsync   
22  QID307       OfficeStackSync   
23  QID327              AISearch   
24  QID328                 AIDev   
25   QID91                    S4   

                           

In [19]:
print(df['qid']) #print one column

0     QID281
1     QID306
2      QID32
3      QID34
4      QID31
5      QID29
6     QID278
7     QID322
8     QID279
9       QID6
10     QID50
11     QID51
12     QID61
13    QID233
14    QID262
15    QID263
16    QID264
17    QID265
18    QID275
19    QID274
20     QID71
21    QID282
22    QID307
23    QID327
24    QID328
25     QID91
Name: qid, dtype: object


In [20]:
lst = df['qid'] # Convert in list a column
print('Printing the list')
print(lst, type(lst))

Printing the list
0     QID281
1     QID306
2      QID32
3      QID34
4      QID31
5      QID29
6     QID278
7     QID322
8     QID279
9       QID6
10     QID50
11     QID51
12     QID61
13    QID233
14    QID262
15    QID263
16    QID264
17    QID265
18    QID275
19    QID274
20     QID71
21    QID282
22    QID307
23    QID327
24    QID328
25     QID91
Name: qid, dtype: object <class 'pandas.core.series.Series'>


In [21]:
print('Printing each element')
for i in lst:
    print(i)
# print(lst[1])

Printing each element
QID281
QID306
QID32
QID34
QID31
QID29
QID278
QID322
QID279
QID6
QID50
QID51
QID61
QID233
QID262
QID263
QID264
QID265
QID275
QID274
QID71
QID282
QID307
QID327
QID328
QID91


## Numpy( Numerical pytho)n

In [1]:
# Arrays (similar to lists, but works 50 times faster!) 
# Contigous memory locations (‘C’ concept of the array)
# Access and manipulate easier
# Written in C / C++
import numpy as np
print(np.__version__)

1.26.1


In [2]:
# 1-D Array
arr = np.array([2, 5, 6, 9, 7, 12])
print(id(arr), id(arr[0]))

for i in range(0,len(arr)):
    print(i, arr[i], id(arr[i]))

1836754373776 1836992512656
0 2 1836992518256
1 5 1836992512176
2 6 1836992518384
3 9 1836992512656
4 7 1836992512176
5 12 1836992518384


In [3]:
print(arr.itemsize, arr.strides)

4 (4,)


In [4]:
# 2-D Array
arr1 = np.array([[2, 5, 6, 9, 7, 12], [5, 8, 7, 11, 31, 0]])

print(id(arr1), id(arr1[0]))
for i in range(0,len(arr1)):
    print(i, arr1[i], id(arr1[i]))

1836754373200 1836993332400
0 [ 2  5  6  9  7 12] 1836993332208
1 [ 5  8  7 11 31  0] 1836993332208


In [5]:
print(arr1.itemsize, arr1.strides)

4 (24, 4)


In [6]:
a = np.array(42)
b = np.array([2, 5, 6, 9, 7, 12])
c = np.array([[2,7, 12], [5, 8, 0]])
d = np.array([[2, 5, 6], [9, 7, 12], [5, 8, 7], [11, 31, 0]])
print(a)
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.data)
print(b.ndim, b.shape, b.size, b.dtype, b.itemsize, b.data)
print(c.ndim, c.shape, c.size, c.dtype, c.itemsize, c.data)
print(d.ndim, d.shape, d.size, d.dtype, d.itemsize, d.data)

42
0 () 1 int32 4 <memory at 0x0000026B3B82CA40>
1 (6,) 6 int32 4 <memory at 0x0000026B4BC6CDC0>
2 (2, 3) 6 int32 4 <memory at 0x0000026B4C114790>
2 (4, 3) 12 int32 4 <memory at 0x0000026B4C114790>


In [7]:
# Reshape given array in matrix
e = np.arange(15).reshape(3, 5)
print(e)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [9]:
Zeros= np.zeros((3, 5))
print(Zeros)

Ones= np.ones((2, 4, 5))
print(Ones)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [10]:
emp= np.empty((4, 6))
print(emp)

[[4.67296746e-307 1.69121096e-306 7.56602523e-307 1.89146896e-307
  7.56571288e-307 3.11525958e-307]
 [1.24610723e-306 1.37962320e-306 1.29060871e-306 2.22518251e-306
  1.33511969e-306 1.78022342e-306]
 [1.05700345e-307 3.11525958e-307 1.69118108e-306 8.06632139e-308
  1.20160711e-306 1.69119330e-306]
 [1.33511018e-306 6.23059726e-307 1.60219035e-306 1.33511969e-306
  1.69119330e-306 1.42410974e-306]]


In [11]:
ran = np.arange(1, 5, 0.5)
print(ran)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [33]:
from numpy import pi
x = np.linspace(0, 2, 9)
print(x)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [34]:
x = np.linspace(0, 2*pi, 100)
y = np.sin(x)
print(y)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769

In [35]:
# Reshape given array in matrix
b = np.arange(10).reshape(2, 5)
print(b)
print()
c = np.arange(24).reshape(2, 3, 4)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [37]:
# b = np.arange(10).reshape(2, 4) # It will show error
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [38]:
a = np.array([2, 5, 6, 9, 7, 12])
b = np.arange(6)
print(a-b)
print(b**2)
print(np.sin(a))

[2 4 4 6 3 7]
[ 0  1  4  9 16 25]
[ 0.90929743 -0.95892427 -0.2794155   0.41211849  0.6569866  -0.53657292]


In [40]:
x = np.array([[3, 4], [8, 9]])
y = np.array([[1, 3], [5, 8]])

print(x.dot(y))
print(x @ y)


[[23 41]
 [53 96]]
[[23 41]
 [53 96]]
